/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Live */
    get: operations["health_live_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Ready */
    get: operations["health_ready_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/contract/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Prova de vida do contrato-base de sucesso (Doc 06 §4.1) */
    get: operations["contract_ping_api_v1_contract_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/interest/simple": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Calcula juros simples (Doc 15 §3). */
    post: operations["post_juros_simples_api_v1_interest_simple_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/interest/compound": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Calcula juros compostos (Doc 15 §4), aporte mensal opcional. */
    post: operations["post_juros_compostos_api_v1_interest_compound_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/interest/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Compara simples × compostos sobre a mesma entrada. */
    post: operations["post_comparar_juros_api_v1_interest_compare_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/amortization/price": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Calcula tabela PRICE de amortizacao. */
    post: operations["post_amortizacao_price_api_v1_amortization_price_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/amortization/sac": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Calcula tabela SAC de amortizacao. */
    post: operations["post_amortizacao_sac_api_v1_amortization_sac_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/amortization/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Compara PRICE e SAC para as mesmas premissas. */
    post: operations["post_comparar_amortizacao_api_v1_amortization_compare_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/diagnostic/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Executa o diagnóstico financeiro completo. */
    post: operations["post_diagnostic_analyze_api_v1_diagnostic_analyze_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/financing/real_estate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Simula financiamento imobiliario com sistema PRICE ou SAC. */
    post: operations["post_financing_real_estate_api_v1_financing_real_estate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/financing/real_estate/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Compara PRICE x SAC para os mesmos parametros de financiamento imobiliario. */
    post: operations["post_financing_real_estate_compare_api_v1_financing_real_estate_compare_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AmortizationPeriodRow
     * @description Linha da tabela de amortizacao serializada pela API.
     */
    AmortizationPeriodRow: {
      /** Periodo */
      periodo: number;
      /** Saldo Inicial */
      saldo_inicial: string;
      /** Juros */
      juros: string;
      /** Amortizacao */
      amortizacao: string;
      /** Parcela */
      parcela: string;
      /** Saldo Final */
      saldo_final: string;
    };
    /**
     * AmortizationSystem
     * @enum {string}
     */
    AmortizationSystem: "PRICE" | "SAC" | "EMPATE";
    /**
     * AnatomiaEncargo
     * @description Decomposicao do encargo mensal do primeiro periodo.
     *
     *     Regra de composicao:
     *         seguros_total = mip_mensal + dfi_dfc_mensal
     *                         (ou seguro_mensal legado quando nao discriminado)
     *         componentes_acessorios = seguros_total + taxa_administracao_mensal + custo_admin_mensal
     *         encargo_mensal_total   = prestacao_financeira + componentes_acessorios
     *
     *     Quando apenas seguro_mensal legado for informado:
     *         mip_mensal = zero, dfi_dfc_mensal = zero, seguros_nao_discriminados = True.
     *     Taxa administrativa nunca entra em seguros_total.
     */
    AnatomiaEncargo: {
      /** Amortizacao */
      amortizacao: string;
      /** Juros */
      juros: string;
      /** Prestacao Financeira */
      prestacao_financeira: string;
      /** Mip Mensal */
      mip_mensal: string;
      /** Dfi Dfc Mensal */
      dfi_dfc_mensal: string;
      /** Seguros Total */
      seguros_total: string;
      /** Seguros Nao Discriminados */
      seguros_nao_discriminados: boolean;
      /** Taxa Administracao Mensal */
      taxa_administracao_mensal: string;
      /** Custo Admin Mensal */
      custo_admin_mensal: string;
      /** Componentes Acessorios */
      componentes_acessorios: string;
      /** Encargo Mensal Total */
      encargo_mensal_total: string;
      /** Seguro Mensal */
      seguro_mensal: string;
      /** Tarifa Mensal */
      tarifa_mensal: string;
      /** Encargos */
      encargos: string;
      /** Pct Amortizacao */
      pct_amortizacao: string;
      /** Pct Juros */
      pct_juros: string;
      /** Pct Prestacao Financeira */
      pct_prestacao_financeira: string;
      /** Pct Mip */
      pct_mip: string;
      /** Pct Dfi Dfc */
      pct_dfi_dfc: string;
      /** Pct Seguros */
      pct_seguros: string;
      /** Pct Taxa Administracao */
      pct_taxa_administracao: string;
      /** Pct Custo Admin */
      pct_custo_admin: string;
      /** Pct Encargos */
      pct_encargos: string;
      /** Pct Seguro */
      pct_seguro: string;
      /** Pct Tarifa */
      pct_tarifa: string;
    };
    /**
     * CompararJurosIn
     * @description Corpo da requisição para comparar simples × compostos.
     */
    CompararJurosIn: {
      /**
       * Principal
       * @description Valor presente (PV) em BRL.
       */
      principal: number | string;
      /**
       * Taxa Mensal
       * @description Taxa mensal como decimal puro (ex.: 0.01 = 1% a.m.).
       */
      taxa_mensal: number | string;
      /**
       * Prazo Meses
       * @description Prazo em meses.
       */
      prazo_meses: number;
    };
    /**
     * CompararJurosOut
     * @description Carga útil (``data``) da resposta de comparação.
     *
     *     Campos (na ordem canônica do envelope):
     *         - ``summary``        — ``SummaryComparar`` com PV, taxa, prazo,
     *           montantes simples/composto, diferença e razão.
     *         - ``tables``         — ``TablesComparar`` com ``simple`` e
     *           ``compound`` aninhados sob um único campo.
     *         - ``charts``         — lista com um único ``Chart`` contendo
     *           duas séries (``simples`` e ``composto``), prontos para
     *           renderização comparativa no frontend.
     *         - ``interpretation`` — bloco pedagógico (headline + body).
     *         - ``alerts``         — lista (usualmente vazia) de alertas
     *           não-bloqueantes.
     */
    CompararJurosOut: {
      summary: components["schemas"]["SummaryComparar"];
      tables?: components["schemas"]["TablesComparar"];
      /** Charts */
      charts?: components["schemas"]["app__schemas__interest__base__Chart"][];
      interpretation: components["schemas"]["app__schemas__interest__base__Interpretation"];
      /** Alerts */
      alerts?: components["schemas"]["app__schemas__interest__base__Alert"][];
    };
    /**
     * CompareAmortizationIn
     * @description Corpo da requisicao para comparar PRICE e SAC.
     */
    CompareAmortizationIn: {
      /**
       * Principal
       * @description Valor presente financiado em BRL. Deve ser maior que zero.
       */
      principal: number | string;
      /**
       * Taxa Periodo
       * @description Taxa por periodo como decimal puro (ex.: 0.01 = 1%).
       */
      taxa_periodo: number | string;
      /**
       * N Periodos
       * @description Quantidade de periodos da amortizacao.
       */
      n_periodos: number;
    };
    /**
     * CompareAmortizationOut
     * @description Carga util (data) da resposta comparativa PRICE x SAC.
     */
    CompareAmortizationOut: {
      summary: components["schemas"]["CompareSummary"];
      tables?: components["schemas"]["TablesCompareAmortization"];
      /** Charts */
      charts?: components["schemas"]["app__schemas__amortization__base__Chart"][];
      interpretation: components["schemas"]["app__schemas__amortization__base__Interpretation"];
      /** Alerts */
      alerts?: components["schemas"]["app__schemas__amortization__base__Alert"][];
    };
    /** CompareSummary */
    CompareSummary: {
      /** Principal */
      principal: string;
      /** Taxa Periodo */
      taxa_periodo: string;
      /** N Periodos */
      n_periodos: number;
      price: components["schemas"]["PriceSummary"];
      sac: components["schemas"]["SacSummary"];
      /**
       * Diferenca Juros
       * @description PRICE.total_juros - SAC.total_juros.
       */
      diferenca_juros: string;
      /**
       * Diferenca Total Pago
       * @description PRICE.total_pago - SAC.total_pago.
       */
      diferenca_total_pago: string;
      menor_total_juros: components["schemas"]["AmortizationSystem"];
    };
    /**
     * ComponenteCet
     * @description Componente individual do CET demonstrativo educacional.
     *
     *     Naturezas:
     *         calculado        - derivado das entradas com formula precisa
     *         informado        - fornecido pelo usuário como entrada
     *         nao_calculado    - existe no CET real mas nao modelado aqui
     *         alerta           - custo mencionado para consciencia, sem valor calculado
     *
     *     Categorias pedagogicas:
     *         base_operacao          - dados da operacao (nao sao custos)
     *         componente_encargo     - entra no encargo mensal
     *         componente_cet         - impacta o CET demonstrativo
     *         custo_inicial          - custo fora do encargo mensal (alerta)
     *         totalizador_indicador  - total ou indicador derivado
     */
    ComponenteCet: {
      /** Id */
      id: string;
      /** Nome */
      nome: string;
      /**
       * Natureza
       * @enum {string}
       */
      natureza: "calculado" | "informado" | "nao_calculado" | "alerta";
      /**
       * Categoria
       * @enum {string}
       */
      categoria:
        | "base_operacao"
        | "componente_encargo"
        | "componente_cet"
        | "custo_inicial"
        | "totalizador_indicador";
      /** Valor Total */
      valor_total: string;
      /** Valor Mensal Referencia */
      valor_mensal_referencia: string;
      /** Pct Sobre Financiado */
      pct_sobre_financiado: string;
      /** Pct Sobre Total Pago */
      pct_sobre_total_pago: string;
      /** Pct Sobre Custo Financeiro Total */
      pct_sobre_custo_financeiro_total: string;
      /** Entra No Encargo Mensal */
      entra_no_encargo_mensal: boolean;
      /** Entra No Custo Total Educacional */
      entra_no_custo_total_educacional: boolean;
      /** Formula */
      formula: string;
      /** Explicacao */
      explicacao: string;
    };
    /**
     * DiagnosticAlertResponse
     * @description Alerta educativo retornado pelo diagnóstico.
     */
    DiagnosticAlertResponse: {
      /**
       * Code
       * @description Identificador estável em UPPER_SNAKE_CASE.
       */
      code: string;
      /**
       * Level
       * @description Severidade do alerta.
       * @enum {string}
       */
      level: "info" | "warning" | "critical";
      /**
       * Dimension
       * @description Dimensão financeira afetada.
       */
      dimension: string;
    };
    /**
     * DiagnosticAnalyzeRequest
     * @description Corpo da requisição para o diagnóstico financeiro.
     */
    DiagnosticAnalyzeRequest: {
      /**
       * Renda Mensal
       * @description Renda líquida mensal total em BRL. Deve ser maior que zero.
       */
      renda_mensal: number | string;
      /**
       * Total Despesas Fixas
       * @description Total de despesas fixas mensais em BRL.
       */
      total_despesas_fixas: number | string;
      /**
       * Total Despesas Variaveis
       * @description Total de despesas variáveis mensais em BRL.
       */
      total_despesas_variaveis: number | string;
      /**
       * Total Dividas Mensais
       * @description Total de parcelas mensais de dívidas em BRL.
       */
      total_dividas_mensais: number | string;
      /**
       * Total Reserva Atual
       * @description Reserva de emergência disponível em BRL.
       */
      total_reserva_atual: number | string;
    };
    /**
     * DiagnosticAnalyzeResponseData
     * @description Carga útil (data) da resposta do diagnóstico financeiro.
     */
    DiagnosticAnalyzeResponseData: {
      /** Renda Mensal */
      renda_mensal: string;
      /** Total Despesas Fixas */
      total_despesas_fixas: string;
      /** Total Despesas Variaveis */
      total_despesas_variaveis: string;
      /** Total Dividas Mensais */
      total_dividas_mensais: string;
      /** Total Reserva Atual */
      total_reserva_atual: string;
      /** Sobra Mensal */
      sobra_mensal: string;
      /** Despesas Essenciais Mensais */
      despesas_essenciais_mensais: string;
      /** Comprometimento Percentual */
      comprometimento_percentual: string;
      /** Sobra Percentual */
      sobra_percentual: string;
      /** Reserva Em Meses */
      reserva_em_meses: string;
      /** Comprometimento Nivel */
      comprometimento_nivel: string;
      /** Reserva Nivel */
      reserva_nivel: string;
      /** Sobra Nivel */
      sobra_nivel: string;
      /** Pontos Comprometimento */
      pontos_comprometimento: number;
      /** Pontos Reserva */
      pontos_reserva: number;
      /** Pontos Sobra */
      pontos_sobra: number;
      /** Score */
      score: number;
      /** Saude Nivel */
      saude_nivel: string;
      /** Alertas */
      alertas: components["schemas"]["DiagnosticAlertResponse"][];
    };
    /**
     * FinanciamentoChartData
     * @description Dados preparados para graficos do frontend.
     */
    FinanciamentoChartData: {
      /** Saldo Devedor */
      saldo_devedor?: components["schemas"]["FinanciamentoChartPoint"][];
      /** Prestacoes */
      prestacoes?: components["schemas"]["FinanciamentoChartPoint"][];
      /** Juros Amortizacao */
      juros_amortizacao?: components["schemas"]["FinanciamentoJurosAmortizacaoPoint"][];
    };
    /**
     * FinanciamentoChartPoint
     * @description Ponto simples para graficos financeiros.
     */
    FinanciamentoChartPoint: {
      /** Periodo */
      periodo: number;
      /** Valor */
      valor: string;
    };
    /**
     * FinanciamentoComparacaoEducacional
     * @description Resumo educacional da comparacao entre PRICE e SAC.
     */
    FinanciamentoComparacaoEducacional: {
      /** Diferenca Primeira Prestacao Financeira */
      diferenca_primeira_prestacao_financeira: string;
      /** Diferenca Ultima Prestacao Financeira */
      diferenca_ultima_prestacao_financeira: string;
      /** Diferenca Primeiro Encargo Mensal */
      diferenca_primeiro_encargo_mensal: string;
      /** Diferenca Ultimo Encargo Mensal */
      diferenca_ultimo_encargo_mensal: string;
      /** Diferenca Total Pago */
      diferenca_total_pago: string;
      /** Diferenca Total Juros */
      diferenca_total_juros: string;
      /** Diferenca Primeira Parcela */
      diferenca_primeira_parcela: string;
      /** Diferenca Ultima Parcela */
      diferenca_ultima_parcela: string;
      /** Comportamento Saldo Devedor */
      comportamento_saldo_devedor: string;
      /** Explicacao Pedagogica */
      explicacao_pedagogica: string;
      /** Interpretacao Dinamica */
      interpretacao_dinamica: string;
      /** Recomendacoes */
      recomendacoes?: string[];
    };
    /**
     * FinanciamentoFonte
     * @description Fonte ou referencia declarada pela resposta educacional.
     */
    FinanciamentoFonte: {
      /** Nome */
      nome: string;
      /** Tipo */
      tipo: string;
      /** Observacao */
      observacao: string;
    };
    /**
     * FinanciamentoFormulaUsada
     * @description Formula financeira usada no calculo.
     */
    FinanciamentoFormulaUsada: {
      /** Nome */
      nome: string;
      /** Expressao */
      expressao: string;
      /** Uso */
      uso: string;
    };
    /**
     * FinanciamentoImobCompareIn
     * @description Corpo da requisicao para comparacao PRICE x SAC com os mesmos dados.
     */
    FinanciamentoImobCompareIn: {
      /**
       * Valor Imovel
       * @description Valor total do imovel em BRL.
       */
      valor_imovel: number | string;
      /**
       * Valor Entrada
       * @description Valor da entrada em BRL. Deve ser menor que valor_imovel.
       */
      valor_entrada: number | string;
      /**
       * Prazo Meses
       * @description Prazo do financiamento em meses (max 600 = 50 anos).
       */
      prazo_meses: number;
      /**
       * Taxa Juros Mensal Percentual
       * @description Taxa de juros mensal em percentual (ex.: 0.7 = 0,7% ao mes).
       */
      taxa_juros_mensal_percentual: number | string;
      /**
       * Seguro Mensal
       * @description Seguro habitacional mensal agregado em BRL (opcional).
       * @default 0.00
       */
      seguro_mensal: number | string;
      /**
       * Tarifa Mensal
       * @description Taxa de administração mensal em BRL (opcional). Não é seguro.
       * @default 0.00
       */
      tarifa_mensal: number | string;
      /**
       * Custo Administrativo Mensal
       * @description Outros custos mensais em BRL (opcional).
       * @default 0.00
       */
      custo_administrativo_mensal: number | string;
      /**
       * Mip Mensal
       * @description MIP mensal em BRL (opcional, separado).
       * @default 0.00
       */
      mip_mensal: number | string;
      /**
       * Dfi Dfc Mensal
       * @description DFI/DFC mensal em BRL (opcional, separado).
       * @default 0.00
       */
      dfi_dfc_mensal: number | string;
      /**
       * Taxa Administracao Mensal
       * @description Taxa de administracao mensal em BRL. Alias de tarifa_mensal.
       * @default 0.00
       */
      taxa_administracao_mensal: number | string;
    };
    /**
     * FinanciamentoImobCompareOut
     * @description Resultado da comparacao PRICE x SAC com os mesmos parametros de entrada.
     */
    FinanciamentoImobCompareOut: {
      price: components["schemas"]["FinanciamentoImobOut"];
      sac: components["schemas"]["FinanciamentoImobOut"];
      comparacao: components["schemas"]["FinanciamentoComparacaoEducacional"];
    };
    /**
     * FinanciamentoImobIn
     * @description Corpo da requisição para simulação de financiamento imobiliario.
     */
    FinanciamentoImobIn: {
      /**
       * Valor Imovel
       * @description Valor total do imovel em BRL.
       */
      valor_imovel: number | string;
      /**
       * Valor Entrada
       * @description Valor da entrada em BRL. Deve ser menor que valor_imovel.
       */
      valor_entrada: number | string;
      /**
       * Prazo Meses
       * @description Prazo do financiamento em meses (max 600 = 50 anos).
       */
      prazo_meses: number;
      /**
       * Taxa Juros Mensal Percentual
       * @description Taxa de juros mensal em percentual (ex.: 0.7 = 0,7% ao mes).
       */
      taxa_juros_mensal_percentual: number | string;
      /** @description Sistema de amortizacao: PRICE ou SAC. */
      sistema_amortizacao: components["schemas"]["SistemaAmortizacaoSchema"];
      /**
       * Seguro Mensal
       * @description Seguro habitacional mensal agregado (MIP + DFI/DFC juntos), em BRL. Opcional. Use mip_mensal + dfi_dfc_mensal para separação individual.
       * @default 0.00
       */
      seguro_mensal: number | string;
      /**
       * Tarifa Mensal
       * @description Taxa de administração mensal em BRL. Não é seguro. Opcional.
       * @default 0.00
       */
      tarifa_mensal: number | string;
      /**
       * Custo Administrativo Mensal
       * @description Outros custos mensais em BRL. Opcional.
       * @default 0.00
       */
      custo_administrativo_mensal: number | string;
      /**
       * Mip Mensal
       * @description MIP mensal em BRL (Seguro de Morte e Invalidez Permanente). Opcional. Quando informado com dfi_dfc_mensal, mantenha seguro_mensal em 0 para evitar dupla contagem.
       * @default 0.00
       */
      mip_mensal: number | string;
      /**
       * Dfi Dfc Mensal
       * @description DFI/DFC mensal em BRL (Seguro de Danos Fisicos ao Imovel / Construcao). Opcional. Informar junto com mip_mensal para separacao completa.
       * @default 0.00
       */
      dfi_dfc_mensal: number | string;
      /**
       * Taxa Administracao Mensal
       * @description Taxa de administracao mensal em BRL. Alias de tarifa_mensal. Não é seguro. Não soma a seguros_total.
       * @default 0.00
       */
      taxa_administracao_mensal: number | string;
    };
    /**
     * FinanciamentoImobOut
     * @description Carga útil (data) da resposta de simulação de financiamento imobiliario.
     */
    FinanciamentoImobOut: {
      summary: components["schemas"]["FinanciamentoImobSummary"];
      /** Parcelas */
      parcelas?: components["schemas"]["FinanciamentoPeriodoRow"][];
      inputs_normalizados: components["schemas"]["FinanciamentoInputsNormalizados"];
      anatomia_encargo: components["schemas"]["AnatomiaEncargo"];
      /** Componentes Cet */
      componentes_cet?: components["schemas"]["ComponenteCet"][];
      memoria_calculo: components["schemas"]["FinanciamentoMemoriaCalculo"];
      /** Formulas Usadas */
      formulas_usadas?: components["schemas"]["FinanciamentoFormulaUsada"][];
      /** Explicacoes Pedagogicas */
      explicacoes_pedagogicas?: string[];
      /** Alertas */
      alertas?: string[];
      /** Fontes */
      fontes?: components["schemas"]["FinanciamentoFonte"][];
      /** Limites */
      limites?: string[];
      metadados_calculo: components["schemas"]["FinanciamentoMetadadosCalculo"];
      /** Mensagens Interface */
      mensagens_interface?: string[];
      chart_data: components["schemas"]["FinanciamentoChartData"];
    };
    /**
     * FinanciamentoImobSummary
     * @description Resumo do financiamento imobiliario.
     */
    FinanciamentoImobSummary: {
      /**
       * Sistema Amortizacao
       * @enum {string}
       */
      sistema_amortizacao: "PRICE" | "SAC";
      /** Valor Imovel */
      valor_imovel: string;
      /** Valor Entrada */
      valor_entrada: string;
      /** Valor Financiado */
      valor_financiado: string;
      /** Prazo Meses */
      prazo_meses: number;
      /** Taxa Juros Mensal */
      taxa_juros_mensal: string;
      /** Taxa Juros Anual Nominal */
      taxa_juros_anual_nominal: string;
      /** Taxa Juros Anual Efetiva */
      taxa_juros_anual_efetiva: string;
      /** Primeira Prestacao Financeira */
      primeira_prestacao_financeira: string;
      /** Ultima Prestacao Financeira */
      ultima_prestacao_financeira: string;
      /** Primeiro Encargo Mensal Total */
      primeiro_encargo_mensal_total: string;
      /** Ultimo Encargo Mensal Total */
      ultimo_encargo_mensal_total: string;
      /** Total Pago */
      total_pago: string;
      /** Total Juros */
      total_juros: string;
      /** Total Amortizado */
      total_amortizado: string;
      /** Total Mip */
      total_mip: string;
      /** Total Dfi Dfc */
      total_dfi_dfc: string;
      /** Total Seguros */
      total_seguros: string;
      /** Total Tarifas */
      total_tarifas: string;
      /** Total Custo Admin */
      total_custo_admin: string;
      /** Seguros Nao Discriminados */
      seguros_nao_discriminados: boolean;
      /** Total Encargos */
      total_encargos: string;
      /** Custo Total */
      custo_total: string;
      /** Custo Financeiro Total */
      custo_financeiro_total: string;
      /** Primeira Parcela */
      primeira_parcela: string;
      /** Ultima Parcela */
      ultima_parcela: string;
    };
    /**
     * FinanciamentoInputsNormalizados
     * @description Entradas normalizadas devolvidas para rastreabilidade educacional.
     */
    FinanciamentoInputsNormalizados: {
      /** Valor Imovel */
      valor_imovel: string;
      /** Valor Entrada */
      valor_entrada: string;
      /** Valor Financiado */
      valor_financiado: string;
      /** Prazo Meses */
      prazo_meses: number;
      /** Taxa Juros Mensal */
      taxa_juros_mensal: string;
      /**
       * Sistema Amortizacao
       * @enum {string}
       */
      sistema_amortizacao: "PRICE" | "SAC";
    };
    /**
     * FinanciamentoJurosAmortizacaoPoint
     * @description Ponto de grafico com decomposicao de juros e amortizacao.
     */
    FinanciamentoJurosAmortizacaoPoint: {
      /** Periodo */
      periodo: number;
      /** Juros */
      juros: string;
      /** Amortizacao */
      amortizacao: string;
    };
    /**
     * FinanciamentoMemoriaCalculo
     * @description Memoria de calculo estruturada para explicar o resultado.
     */
    FinanciamentoMemoriaCalculo: {
      /**
       * Metodo
       * @enum {string}
       */
      metodo: "PRICE" | "SAC";
      entradas: components["schemas"]["FinanciamentoInputsNormalizados"];
      /** Formula */
      formula: string;
      /** Variaveis */
      variaveis: {
        [key: string]: string;
      };
      /** Substituicao */
      substituicao: string;
      /** Arredondamento */
      arredondamento: string;
      primeira_parcela: components["schemas"]["FinanciamentoPeriodoRow"];
      ultima_parcela: components["schemas"]["FinanciamentoPeriodoRow"];
      /** Custo Total */
      custo_total: string;
      /** Resultado Final */
      resultado_final: {
        [key: string]: string;
      };
    } & {
      [key: string]: unknown;
    };
    /**
     * FinanciamentoMetadadosCalculo
     * @description Metadados de rastreabilidade do calculo.
     */
    FinanciamentoMetadadosCalculo: {
      /** Moeda */
      moeda: string;
      /** Criterio Arredondamento */
      criterio_arredondamento: string;
      /** Linhas Tabela */
      linhas_tabela: number;
      /** Prazo Dinamico Respeitado */
      prazo_dinamico_respeitado: boolean;
      /** Contrato Educacional Api */
      contrato_educacional_api: string;
    };
    /**
     * FinanciamentoPeriodoRow
     * @description Linha da tabela de parcelas serializada pela API.
     *
     *     Nomenclatura canonica:
     *         prestacao_financeira = juros + amortizacao
     *         seguro_mensal        = MIP + DFI (campo separado)
     *         tarifa_mensal        = taxa de administracao (campo separado)
     *         custo_admin_mensal   = outros custos mensais (campo separado)
     *         encargos             = seguro + tarifa + custo_admin
     *         encargo_mensal_total = prestacao_financeira + encargos
     *         prestacao            = alias retrocompat = encargo_mensal_total
     */
    FinanciamentoPeriodoRow: {
      /** Numero */
      numero: number;
      /** Saldo Inicial */
      saldo_inicial: string;
      /** Juros */
      juros: string;
      /** Amortizacao */
      amortizacao: string;
      /** Prestacao Financeira */
      prestacao_financeira: string;
      /** Seguro Mensal */
      seguro_mensal: string;
      /** Tarifa Mensal */
      tarifa_mensal: string;
      /** Custo Admin Mensal */
      custo_admin_mensal: string;
      /** Encargos */
      encargos: string;
      /** Encargo Mensal Total */
      encargo_mensal_total: string;
      /** Prestacao */
      prestacao: string;
      /** Saldo Final */
      saldo_final: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * JurosCompostosIn
     * @description Corpo da requisição para juros compostos.
     *
     *     O parâmetro ``aporte_mensal`` é postecipado (aplicado ao final do
     *     período, após a incidência dos juros). Quando ausente ou
     *     ``null``, a simulação é de juros compostos puros
     *     (``FV = PV × (1 + i)^n``).
     */
    JurosCompostosIn: {
      /**
       * Principal
       * @description Valor presente (PV) em BRL.
       */
      principal: number | string;
      /**
       * Taxa Mensal
       * @description Taxa mensal como decimal puro (ex.: 0.01 = 1% a.m.).
       */
      taxa_mensal: number | string;
      /**
       * Prazo Meses
       * @description Prazo em meses (estritamente positivo).
       */
      prazo_meses: number;
      /**
       * Aporte Mensal
       * @description Aporte mensal postecipado (BRL). Opcional; default 0.
       */
      aporte_mensal?: number | string | null;
    };
    /**
     * JurosCompostosOut
     * @description Carga útil (``data``) da resposta de juros compostos.
     */
    JurosCompostosOut: {
      summary: components["schemas"]["SummaryCompostos"];
      /**
       * Tables
       * @description Chave canônica: 'amortizacao'.
       */
      tables?: {
        [key: string]: components["schemas"]["PeriodoCompostoRow"][];
      };
      /** Charts */
      charts?: components["schemas"]["app__schemas__interest__base__Chart"][];
      interpretation: components["schemas"]["app__schemas__interest__base__Interpretation"];
      /** Alerts */
      alerts?: components["schemas"]["app__schemas__interest__base__Alert"][];
    };
    /**
     * JurosSimplesIn
     * @description Corpo da requisição para juros simples.
     *
     *     Validações de borda:
     *         - ``principal >= 0`` e tipo ``Decimal`` (Pydantic v2 coage
     *           string/float para Decimal com precisão preservada).
     *         - ``taxa_mensal >= 0``. Interpretada como decimal puro — 1% a.m.
     *           deve ser enviado como ``"0.01"``, **não** como ``"1"``.
     *         - ``prazo_meses`` estritamente positivo e menor que 1200
     *           (limite superior defensivo — 100 anos de prazo mensal).
     */
    JurosSimplesIn: {
      /**
       * Principal
       * @description Valor presente (PV) em BRL. Envie como string para preservar precisão.
       */
      principal: number | string;
      /**
       * Taxa Mensal
       * @description Taxa mensal como decimal puro (ex.: 0.01 = 1% a.m.).
       */
      taxa_mensal: number | string;
      /**
       * Prazo Meses
       * @description Prazo em meses. Estritamente positivo; limite superior defensivo.
       */
      prazo_meses: number;
    };
    /**
     * JurosSimplesOut
     * @description Carga útil (``data``) da resposta de juros simples.
     */
    JurosSimplesOut: {
      summary: components["schemas"]["SummarySimples"];
      /**
       * Tables
       * @description Chave canônica: 'amortizacao' — tabela período-a-período.
       */
      tables?: {
        [key: string]: components["schemas"]["PeriodoSimplesRow"][];
      };
      /** Charts */
      charts?: components["schemas"]["app__schemas__interest__base__Chart"][];
      interpretation: components["schemas"]["app__schemas__interest__base__Interpretation"];
      /** Alerts */
      alerts?: components["schemas"]["app__schemas__interest__base__Alert"][];
    };
    /**
     * Meta
     * @description Metadados canônicos do envelope de sucesso (Doc 06 §4.1).
     */
    Meta: {
      /**
       * Request Id
       * @description Identificador único da requisição (UUID4), propagado em X-Request-ID.
       */
      request_id: string;
      /**
       * Version
       * @description Versão da API que respondeu (casa com o prefixo /api/v1).
       * @default v1
       */
      version: string;
      /**
       * Generated At
       * Format: date-time
       * @description Timestamp ISO-8601 UTC do momento de geração da resposta.
       */
      generated_at: string;
    };
    /**
     * PeriodoCompostoRow
     * @description Linha da tabela de juros compostos.
     */
    PeriodoCompostoRow: {
      /**
       * Periodo
       * @description Número do período (1-indexed).
       */
      periodo: number;
      /**
       * Saldo Inicial
       * @description Saldo no início do período (BRL, 2 casas).
       */
      saldo_inicial: string;
      /**
       * Juros Periodo
       * @description Juros gerados no período (BRL, 2 casas).
       */
      juros_periodo: string;
      /**
       * Aporte
       * @description Aporte creditado ao final do período (BRL, 2 casas).
       */
      aporte: string;
      /**
       * Saldo Final
       * @description Saldo ao final do período após juros e aporte (BRL, 2 casas).
       */
      saldo_final: string;
    };
    /**
     * PeriodoSimplesRow
     * @description Linha da tabela de juros simples.
     */
    PeriodoSimplesRow: {
      /**
       * Periodo
       * @description Número do período (1-indexed).
       */
      periodo: number;
      /**
       * Saldo Inicial
       * @description Saldo no início do período (BRL, 2 casas).
       */
      saldo_inicial: string;
      /**
       * Juros Periodo
       * @description Juros gerados no período (BRL, 2 casas).
       */
      juros_periodo: string;
      /**
       * Saldo Final
       * @description Saldo ao final do período (BRL, 2 casas).
       */
      saldo_final: string;
    };
    /** PingData */
    PingData: {
      /** Pong */
      pong: boolean;
      /** Echo */
      echo?: string | null;
    };
    /**
     * PriceIn
     * @description Corpo da requisicao para amortizacao PRICE.
     */
    PriceIn: {
      /**
       * Principal
       * @description Valor presente financiado em BRL. Deve ser maior que zero.
       */
      principal: number | string;
      /**
       * Taxa Periodo
       * @description Taxa por periodo como decimal puro (ex.: 0.01 = 1%).
       */
      taxa_periodo: number | string;
      /**
       * N Periodos
       * @description Quantidade de periodos da amortizacao.
       */
      n_periodos: number;
    };
    /**
     * PriceOut
     * @description Carga util (data) da resposta PRICE.
     */
    PriceOut: {
      summary: components["schemas"]["PriceSummary"];
      /** Tables */
      tables?: {
        [key: string]: components["schemas"]["AmortizationPeriodRow"][];
      };
      /** Charts */
      charts?: components["schemas"]["app__schemas__amortization__base__Chart"][];
      interpretation: components["schemas"]["app__schemas__amortization__base__Interpretation"];
      /** Alerts */
      alerts?: components["schemas"]["app__schemas__amortization__base__Alert"][];
    };
    /** PriceSummary */
    PriceSummary: {
      /**
       * Sistema
       * @default PRICE
       * @constant
       */
      sistema: "PRICE";
      /** Principal */
      principal: string;
      /** Taxa Periodo */
      taxa_periodo: string;
      /** N Periodos */
      n_periodos: number;
      /** Parcela */
      parcela: string;
      /** Total Pago */
      total_pago: string;
      /** Total Juros */
      total_juros: string;
      /** Saldo Final */
      saldo_final: string;
    };
    /** ResponseEnvelope[CompararJurosOut] */
    ResponseEnvelope_CompararJurosOut_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["CompararJurosOut"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /** ResponseEnvelope[CompareAmortizationOut] */
    ResponseEnvelope_CompareAmortizationOut_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["CompareAmortizationOut"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /** ResponseEnvelope[DiagnosticAnalyzeResponseData] */
    ResponseEnvelope_DiagnosticAnalyzeResponseData_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["DiagnosticAnalyzeResponseData"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /** ResponseEnvelope[FinanciamentoImobCompareOut] */
    ResponseEnvelope_FinanciamentoImobCompareOut_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["FinanciamentoImobCompareOut"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /** ResponseEnvelope[FinanciamentoImobOut] */
    ResponseEnvelope_FinanciamentoImobOut_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["FinanciamentoImobOut"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /** ResponseEnvelope[JurosCompostosOut] */
    ResponseEnvelope_JurosCompostosOut_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["JurosCompostosOut"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /** ResponseEnvelope[JurosSimplesOut] */
    ResponseEnvelope_JurosSimplesOut_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["JurosSimplesOut"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /** ResponseEnvelope[PingData] */
    ResponseEnvelope_PingData_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["PingData"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /** ResponseEnvelope[PriceOut] */
    ResponseEnvelope_PriceOut_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["PriceOut"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /** ResponseEnvelope[SacOut] */
    ResponseEnvelope_SacOut_: {
      /**
       * Success
       * @description Sempre True em respostas 2xx.
       * @default true
       */
      success: boolean;
      /**
       * Message
       * @description Mensagem curta legível para o consumidor.
       */
      message: string;
      /** @description Carga útil tipada da resposta. */
      data: components["schemas"]["SacOut"];
      /** @description Metadados da resposta. */
      meta: components["schemas"]["Meta"];
    };
    /**
     * SacIn
     * @description Corpo da requisicao para amortizacao SAC.
     */
    SacIn: {
      /**
       * Principal
       * @description Valor presente financiado em BRL. Deve ser maior que zero.
       */
      principal: number | string;
      /**
       * Taxa Periodo
       * @description Taxa por periodo como decimal puro (ex.: 0.01 = 1%).
       */
      taxa_periodo: number | string;
      /**
       * N Periodos
       * @description Quantidade de periodos da amortizacao.
       */
      n_periodos: number;
    };
    /**
     * SacOut
     * @description Carga util (data) da resposta SAC.
     */
    SacOut: {
      summary: components["schemas"]["SacSummary"];
      /** Tables */
      tables?: {
        [key: string]: components["schemas"]["AmortizationPeriodRow"][];
      };
      /** Charts */
      charts?: components["schemas"]["app__schemas__amortization__base__Chart"][];
      interpretation: components["schemas"]["app__schemas__amortization__base__Interpretation"];
      /** Alerts */
      alerts?: components["schemas"]["app__schemas__amortization__base__Alert"][];
    };
    /** SacSummary */
    SacSummary: {
      /**
       * Sistema
       * @default SAC
       * @constant
       */
      sistema: "SAC";
      /** Principal */
      principal: string;
      /** Taxa Periodo */
      taxa_periodo: string;
      /** N Periodos */
      n_periodos: number;
      /** Amortizacao Constante */
      amortizacao_constante: string;
      /** Parcela Inicial */
      parcela_inicial: string;
      /** Parcela Final */
      parcela_final: string;
      /** Total Pago */
      total_pago: string;
      /** Total Juros */
      total_juros: string;
      /** Saldo Final */
      saldo_final: string;
    };
    /**
     * SistemaAmortizacaoSchema
     * @enum {string}
     */
    SistemaAmortizacaoSchema: "PRICE" | "SAC";
    /**
     * SummaryComparar
     * @description Resumo canônico de uma comparação simples × compostos.
     */
    SummaryComparar: {
      /** Principal */
      principal: string;
      /** Taxa Mensal */
      taxa_mensal: string;
      /** Prazo Meses */
      prazo_meses: number;
      /** Montante Simples */
      montante_simples: string;
      /** Montante Composto */
      montante_composto: string;
      /**
       * Diferenca
       * @description montante_composto - montante_simples (BRL).
       */
      diferenca: string;
      /**
       * Razao
       * @description montante_composto / montante_simples, como string (6 casas).
       */
      razao: string;
    };
    /**
     * SummaryCompostos
     * @description Resumo canônico de uma simulação de juros compostos.
     */
    SummaryCompostos: {
      /**
       * Principal
       * @description PV de entrada.
       */
      principal: string;
      /**
       * Taxa Mensal
       * @description Taxa mensal (ex.: 0.010000).
       */
      taxa_mensal: string;
      /** Prazo Meses */
      prazo_meses: number;
      /**
       * Aporte Mensal
       * @description Aporte mensal postecipado (0 quando ausente).
       */
      aporte_mensal: string;
      /**
       * Juros Totais
       * @description Juros acumulados (BRL).
       */
      juros_totais: string;
      /**
       * Total Aportado
       * @description Soma dos aportes (BRL).
       */
      total_aportado: string;
      /**
       * Total Investido
       * @description principal + total_aportado (BRL).
       */
      total_investido: string;
      /**
       * Montante Final
       * @description Saldo final (BRL).
       */
      montante_final: string;
    };
    /**
     * SummarySimples
     * @description Resumo canônico de uma simulação de juros simples.
     */
    SummarySimples: {
      /**
       * Principal
       * @description PV de entrada.
       */
      principal: string;
      /**
       * Taxa Mensal
       * @description Taxa mensal (ex.: 0.010000).
       */
      taxa_mensal: string;
      /** Prazo Meses */
      prazo_meses: number;
      /**
       * Juros Totais
       * @description Juros acumulados (BRL).
       */
      juros_totais: string;
      /**
       * Montante Final
       * @description FV = PV + J (BRL).
       */
      montante_final: string;
    };
    /**
     * TablesComparar
     * @description Agrupamento canônico das tabelas no endpoint ``/compare``.
     *
     *     A forma preserva o campo único ``tables`` do envelope canônico
     *     (``summary/tables/charts/interpretation/alerts``) e aninha, sob
     *     chaves estáveis, as duas tabelas período-a-período que o
     *     endpoint precisa devolver.
     *
     *     Chaves:
     *         - ``simple``   — tabela de juros simples (``PeriodoSimplesRow``).
     *         - ``compound`` — tabela de juros compostos (``PeriodoCompostoRow``).
     */
    TablesComparar: {
      /**
       * Simple
       * @description Tabela período-a-período — juros simples.
       */
      simple?: components["schemas"]["PeriodoSimplesRow"][];
      /**
       * Compound
       * @description Tabela período-a-período — juros compostos.
       */
      compound?: components["schemas"]["PeriodoCompostoRow"][];
    };
    /** TablesCompareAmortization */
    TablesCompareAmortization: {
      /** Price */
      price?: components["schemas"]["AmortizationPeriodRow"][];
      /** Sac */
      sac?: components["schemas"]["AmortizationPeriodRow"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** Alert */
    app__schemas__amortization__base__Alert: {
      /** Code */
      code: string;
      /**
       * Severity
       * @default info
       * @enum {string}
       */
      severity: "info" | "warning";
      /** Message */
      message: string;
    };
    /** Chart */
    app__schemas__amortization__base__Chart: {
      /**
       * X Label
       * @default Periodo
       */
      x_label: string;
      /**
       * Y Label
       * @default Saldo devedor (BRL)
       */
      y_label: string;
      /** Series */
      series: components["schemas"]["app__schemas__amortization__base__ChartSeries"][];
    };
    /** ChartSeries */
    app__schemas__amortization__base__ChartSeries: {
      /** Label */
      label: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "price" | "sac";
      /** Points */
      points: string[];
    };
    /** Interpretation */
    app__schemas__amortization__base__Interpretation: {
      /** Headline */
      headline: string;
      /** Body */
      body: string;
    };
    /**
     * Alert
     * @description Alerta pedagógico/operacional anexado à resposta.
     */
    app__schemas__interest__base__Alert: {
      /**
       * Code
       * @description Código estável do alerta (UPPER_SNAKE_CASE).
       */
      code: string;
      /**
       * Severity
       * @description Severidade do alerta (nunca 'error' aqui — erros usam Problem).
       * @default info
       * @enum {string}
       */
      severity: "info" | "warning";
      /**
       * Message
       * @description Mensagem legível em PT-BR.
       */
      message: string;
    };
    /**
     * Chart
     * @description Meta-gráfico de evolução de saldo.
     *
     *     Não renderiza: descreve. Frontend é responsável por transformar
     *     isto em visualização (Chart.js, Recharts, etc.).
     */
    app__schemas__interest__base__Chart: {
      /**
       * X Label
       * @default Período (meses)
       */
      x_label: string;
      /**
       * Y Label
       * @default Saldo (BRL)
       */
      y_label: string;
      /** Series */
      series: components["schemas"]["app__schemas__interest__base__ChartSeries"][];
    };
    /**
     * ChartSeries
     * @description Série de pontos de um gráfico de evolução.
     */
    app__schemas__interest__base__ChartSeries: {
      /**
       * Label
       * @description Rótulo humano da série.
       */
      label: string;
      /**
       * Kind
       * @description Tipo de cálculo que gerou a série.
       * @enum {string}
       */
      kind: "simples" | "composto";
      /**
       * Points
       * @description Saldo ao final de cada período (BRL). ``len == prazo_meses``.
       */
      points: string[];
    };
    /**
     * Interpretation
     * @description Bloco pedagógico narrativo — explica o resultado em PT-BR.
     */
    app__schemas__interest__base__Interpretation: {
      /**
       * Headline
       * @description Frase curta e direta com o resultado principal.
       */
      headline: string;
      /**
       * Body
       * @description Explicação narrativa (1–3 parágrafos).
       */
      body: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  health_live_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  health_ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  contract_ping_api_v1_contract_ping_get: {
    parameters: {
      query?: {
        echo?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_PingData_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_juros_simples_api_v1_interest_simple_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JurosSimplesIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_JurosSimplesOut_"];
        };
      };
      /** @description Validação de entrada falhou (Problem+JSON). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": unknown;
        };
      };
    };
  };
  post_juros_compostos_api_v1_interest_compound_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JurosCompostosIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_JurosCompostosOut_"];
        };
      };
      /** @description Validação de entrada falhou (Problem+JSON). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": unknown;
        };
      };
    };
  };
  post_comparar_juros_api_v1_interest_compare_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompararJurosIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_CompararJurosOut_"];
        };
      };
      /** @description Validação de entrada falhou (Problem+JSON). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": unknown;
        };
      };
    };
  };
  post_amortizacao_price_api_v1_amortization_price_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PriceIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_PriceOut_"];
        };
      };
      /** @description Validacao de entrada falhou (Problem+JSON). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": unknown;
        };
      };
    };
  };
  post_amortizacao_sac_api_v1_amortization_sac_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SacIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_SacOut_"];
        };
      };
      /** @description Validacao de entrada falhou (Problem+JSON). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": unknown;
        };
      };
    };
  };
  post_comparar_amortizacao_api_v1_amortization_compare_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompareAmortizationIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_CompareAmortizationOut_"];
        };
      };
      /** @description Validacao de entrada falhou (Problem+JSON). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": unknown;
        };
      };
    };
  };
  post_diagnostic_analyze_api_v1_diagnostic_analyze_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DiagnosticAnalyzeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_DiagnosticAnalyzeResponseData_"];
        };
      };
      /** @description Validação de entrada falhou (Problem+JSON). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": unknown;
        };
      };
    };
  };
  post_financing_real_estate_api_v1_financing_real_estate_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FinanciamentoImobIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_FinanciamentoImobOut_"];
        };
      };
      /** @description Validacao de entrada falhou (Problem+JSON). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": unknown;
        };
      };
    };
  };
  post_financing_real_estate_compare_api_v1_financing_real_estate_compare_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FinanciamentoImobCompareIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseEnvelope_FinanciamentoImobCompareOut_"];
        };
      };
      /** @description Validacao de entrada falhou (Problem+JSON). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": unknown;
        };
      };
    };
  };
}
