"""initial schema

Revision ID: 89360d9f55b5
Revises:
Create Date: 2026-04-17 02:10:41.726046+00:00

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "89360d9f55b5"  # pragma: allowlist secret
down_revision: str | None = None  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
